### ISSUE TITLE
Segmentation fault in demo

### ISSUE THREAD

**Issue by vi** [dtschump/gmic-community#73]
```
[gmic] G'MIC encountered a fatal error (Segmentation fault). Please submit a bug report, at: https://github.com/dtschump/gmic-community/issues
```

Steps to reproduce:

1. Start gmic demo
2. Click at "Color curves" demo multiple times fast enough
3. Crashes or unusable black windows appear.

gdb log:

```
$ gdb -args ./gmic
...
(gdb) r
Starting program: /mnt/src/git/gmic/build/gmic 
...
  gmic: GREYC's Magic for Image Computing. 
 
        Version 2.0.0, Copyright (c) 2008-2017, David Tschumperle. 
        (http://gmic.eu)

[gmic] No commands, options or data provided (type 'gmic -h' to get help).
[gmic] Running in demo mode.[New Thread 0x7fffdf265700 (LWP 29927)]
...
 ------ Color curves ----------------------------------------------------------------------------
...
 ------ Color curves ----------------------------------------------------------------------------
...
 ------ Color curves ----------------------------------------------------------------------------
...
*** Error in `/mnt/src/git/gmic/build/gmic': corrupted double-linked list: 0x00007fffd402bcc0 ***
terminate called after throwing an instance of 'cimg_library::CImgInstanceException'
  what():  [instance(0,0,0,0,(nil),non-shared)] CImg<char>::assign(): Failed to allocate memory (7188900352.0 Gio) for image (1953394534,1819239200,1547530863,1869767202).
[Thread 0x7fffdda62700 (LWP 29930) exited]
[Thread 0x7fffde263700 (LWP 29929) exited]
[Thread 0x7fffdea64700 (LWP 29928) exited]
[Thread 0x7fffdf265700 (LWP 29927) exited]

Thread 8 "gmic" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffdc988700 (LWP 29951)]
0x00007ffff17e4067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff17e4067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff17e5448 in __GI_abort () at abort.c:89
#2  0x00007ffff18221b4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff1917210 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff182798e in malloc_printerr (action=1, str=0x7ffff19132ec "corrupted double-linked list", ptr=<optimized out>) at malloc.c:4996
#4  0x00007ffff1827c14 in malloc_consolidate (av=av@entry=0x7fffd4000020) at malloc.c:4157
#5  0x00007ffff1828641 in _int_free (av=0x7fffd4000020, p=<optimized out>, have_lock=0) at malloc.c:4057
#6  0x000000000072d6ec in cimg_library::CImg<char>::assign(char const*, unsigned int, unsigned int, unsigned int, unsigned int) ()
#7  0x000000000072ea39 in void cimg_library::cimg::swap<cimg_library::CImg<char> >(cimg_library::CImg<char>&, cimg_library::CImg<char>&) ()
#8  0x00000000008d9a19 in gmic& gmic::_run<float>(cimg_library::CImgList<char> const&, unsigned int&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, unsigned int const*, bool*, char const*, cimg_library::CImg<unsigned int> const*) ()
#9  0x0000000000877735 in gmic& gmic::_run<float>(cimg_library::CImgList<char> const&, unsigned int&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, unsigned int const*, bool*, char const*, cimg_library::CImg<unsigned int> const*) ()
#10 0x0000000000877735 in gmic& gmic::_run<float>(cimg_library::CImgList<char> const&, unsigned int&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, unsigned int const*, bool*, char const*, cimg_library::CImg<unsigned int> const*) ()
#11 0x0000000000877735 in gmic& gmic::_run<float>(cimg_library::CImgList<char> const&, unsigned int&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, unsigned int const*, bool*, char const*, cimg_library::CImg<unsigned int> const*) ()
#12 0x00000000008d8e1e in gmic& gmic::_run<float>(cimg_library::CImgList<char> const&, unsigned int&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, unsigned int const*, bool*, char const*, cimg_library::CImg<unsigned int> const*) ()
#13 0x000000000050706e in void* gmic_parallel<float>(void*) ()
#14 0x00007ffff27a1064 in start_thread (arg=0x7fffdc988700) at pthread_create.c:309
#15 0x00007ffff189762d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) bt full
#0  0x00007ffff17e4067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 29922
        selftid = 29951
#1  0x00007ffff17e5448 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 0, 140737245114642, 102, 140737245109854, 1, 140736750334064, 0, 0, 0, 140736894190427, 140737248566592, 7995769707, 0, 4294967296, 4294967297}}, sa_flags = 1, sa_restorer = 0x3}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff18221b4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff1917210 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
        ap = {{gp_offset = 40, fp_offset = 1, overflow_arg_area = 0x7fffdc95c3d0, reg_save_area = 0x7fffdc95c360}}
        fd = 13
        on_2 = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
#3  0x00007ffff182798e in malloc_printerr (action=1, str=0x7ffff19132ec "corrupted double-linked list", ptr=<optimized out>) at malloc.c:4996
        buf = "00007fffd402bcc0"
        cp = <optimized out>
#4  0x00007ffff1827c14 in malloc_consolidate (av=av@entry=0x7fffd4000020) at malloc.c:4157
        fb = <optimized out>
        maxfb = 0x7fffd4000070
        p = 0x7fffd402bcc0
        nextp = 0x0
        unsorted_bin = 0x7fffd4000078
        first_unsorted = <optimized out>
        nextchunk = 0x7fffd402c0a0
        size = 992
        nextsize = 272
        prevsize = <optimized out>
        nextinuse = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        __func__ = "malloc_consolidate"
#5  0x00007ffff1828641 in _int_free (av=0x7fffd4000020, p=<optimized out>, have_lock=0) at malloc.c:4057
        size = 6982048
        fb = <optimized out>
        nextchunk = 0x7fffd4c5c3b0
        nextsize = 1876080
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        errstr = 0x0
        locked = 1
        __func__ = "_int_free"
#6  0x000000000072d6ec in cimg_library::CImg<char>::assign(char const*, unsigned int, unsigned int, unsigned int, unsigned int) ()
No symbol table info available.
#7  0x000000000072ea39 in void cimg_library::cimg::swap<cimg_library::CImg<char> >(cimg_library::CImg<char>&, cimg_library::CImg<char>&) ()
No symbol table info available.
#8  0x00000000008d9a19 in gmic& gmic::_run<float>(cimg_library::CImgList<char> const&, unsigned int&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, unsigned int const*, bool*, char const*, cimg_library::CImg<unsigned int> const*) ()
No symbol table info available.
#9  0x0000000000877735 in gmic& gmic::_run<float>(cimg_library::CImgList<char> const&, unsigned int&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, unsigned int const*, bool*, char const*, cimg_library::CImg<unsigned int> const*) ()
No symbol table info available.
#10 0x0000000000877735 in gmic& gmic::_run<float>(cimg_library::CImgList<char> const&, unsigned int&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, unsigned int const*, bool*, char const*, cimg_library::CImg<unsigned int> const*) ()
No symbol table info available.
#11 0x0000000000877735 in gmic& gmic::_run<float>(cimg_library::CImgList<char> const&, unsigned int&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, unsigned int const*, bool*, char const*, cimg_library::CImg<unsigned int> const*) ()
No symbol table info available.
#12 0x00000000008d8e1e in gmic& gmic::_run<float>(cimg_library::CImgList<char> const&, unsigned int&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, cimg_library::CImgList<float>&, cimg_library::CImgList<char>&, unsigned int const*, bool*, char const*, cimg_library::CImg<unsigned int> const*) ()
No symbol table info available.
#13 0x000000000050706e in void* gmic_parallel<float>(void*) ()
No symbol table info available.
#14 0x00007ffff27a1064 in start_thread (arg=0x7fffdc988700) at pthread_create.c:309
        __res = <optimized out>
        pd = 0x7fffdc988700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736894371584, 7307092429627051366, 0, 140737354125408, 0, 140736894371584, -7307168558056878746, -7307119886792667802}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#15 0x00007ffff189762d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
```

**Comment by dtschump** [comment]
I confirm there is a problem when clicking on the demo menu multiple times.
I'll investigate. Thanks for your report.

**Comment by dtschump** [comment]
I've done a work-around, by allowing only one session of the color curves at a time.
